# Generated by Django 5.1.6 on 2025-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='some_field',
        ),
        migrations.AddField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
